# Generated by Django 5.0.6 on 2024-06-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_agentes_active_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagos',
            options={'ordering': ['-fecha'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AddField(
            model_name='pagos',
            name='acreditado',
            field=models.BooleanField(default=False, verbose_name='Acreditado'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='doc_acreditacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nro de Acreditacion'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='fecha_acreditado',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Acreditado'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='nro_documento',
            field=models.CharField(default='0', max_length=40, verbose_name='Nro de Documento'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='reintegro_gasto',
            field=models.BooleanField(blank=True, default=False, verbose_name='Reintegro de Gasto'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='tipo_pago',
            field=models.CharField(choices=[('Cta_cte', 'Cta_cte'), ('Factura', 'Factura'), ('FCE', 'FCE'), ('Ajuste', 'Ajuste')], default='Cta_cte', max_length=30),
        ),
    ]
