# Generated by Django 5.0.6 on 2024-06-18 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_pagos_options_pagos_acreditado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(blank=True, null=True, upload_to='pagos_imagen')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_pagos', to='api.pagos')),
            ],
            options={
                'verbose_name': 'Imagen Pago',
                'verbose_name_plural': 'Imagen Pagos',
            },
        ),
    ]
