# Generated by Django 5.0.6 on 2024-06-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_imagenpagos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentes',
            name='codigo_agente',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
